### ISSUE TITLE
Sanatize nickname

### ISSUE THREAD

**Issue by iiegor** [iiegor/xat-server#14]
When we update our details the nickname is not sanatized/escaped correctly so we get something like this string: `MyNameÃ????Ã???asÃ??Ã?Â`

**Comment by Hotallday** [comment]
I think is the decoding. Are you sure you're decoding the packets using UTF 8

**Comment by iiegor** [comment]
@Hotallday Oops, you are right! I was converting the buffer to binary :sweat:, fixed. Thanks!
