### ISSUE TITLE
Send room offline users

### ISSUE THREAD

**Issue by iiegor** [iiegor/xat-server#19]
When we connect to an empty chat room, the previous messages are not showing because before we should have sent the offline users that sent that messages.

The message structure we need to send is `<o u="USER_ID(int)" s="1" N="USER_NAME(str)" a="USER_AVATAR(str)" h="USER_HOME(str)" n="USER_NICKNAME(str)" />`

**Comment by huumanoid** [comment]
And also we need powers list. It is very annoying when offline users has ugly broken nicknames even if they are subscribers
